/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SLEEP_CONTROL 0x12345678
#define SLEEP_CONTROL_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define set_sleep_duration 1
extern  int * set_sleep_duration_1(int *, CLIENT *);
extern  int * set_sleep_duration_1_svc(int *, struct svc_req *);
extern int sleep_control_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define set_sleep_duration 1
extern  int * set_sleep_duration_1();
extern  int * set_sleep_duration_1_svc();
extern int sleep_control_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
