/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int kids;
	int secs;
};
typedef struct numbers numbers;

#define SLEEP_CONTROL 0x12345678
#define SLEEP_CONTROL_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define set_sleep_duration 1
extern  int * set_sleep_duration_1(numbers *, CLIENT *);
extern  int * set_sleep_duration_1_svc(numbers *, struct svc_req *);
extern int sleep_control_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define set_sleep_duration 1
extern  int * set_sleep_duration_1();
extern  int * set_sleep_duration_1_svc();
extern int sleep_control_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
