/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


void
sleep_control_1(char *host, int kids, int secs)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  set_sleep_duration_1_arg;
	set_sleep_duration_1_arg.kids = kids;
	set_sleep_duration_1_arg.secs = secs;

#ifndef	DEBUG
	clnt = clnt_create (host, SLEEP_CONTROL, SLEEP_CONTROL_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = set_sleep_duration_1(&set_sleep_duration_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]) {
	char *host;
	int kids;
	int secs;

	if (argc < 2) {
		printf ("usage: %s <server_host> <kids> <secs>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	kids = atoi(argv[2]);
	secs = atoi(argv[3]);

	sleep_control_1 (host, kids, secs);
exit (0);
}
